export {
  attribute as Attribute,
  hashKey as HashKey,
  rangeKey as RangeKey,
  table as Table,
  autoGeneratedHashKey as AutoGeneratedHashKey,
  versionAttribute as VersionAttribute,
} from '@aws/dynamodb-data-mapper-annotations';

export * from './dynamodb.constants';
export * from './dynamodb.decorators';
export * from './dynamodb.interface';
export * from './dynamodb.module';
